### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/actividad-1-infografia-NoeliaGlez#2]
[infografía.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-NoeliaGlez/files/9437065/infografia.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 19
Recomendación: Usar una sola página

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
